<a href="https://colab.research.google.com/github/jj-it-lab/Data-Analysis-with-Open-Source/blob/main/%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_5%EA%B0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 오픈소스 기반 데이터 분석 5강 - 데이터 저장

## 5-1 CSV 형식 저장

In [29]:
import pandas as pd

data = {
    'student_id': [101, 102, 103, 104, 105],
    'database_score': [85, 76, 92, 63, 88],
    'cloudcomputing_score': [78, 82, 95, 70, 84],
    'python_score': [92, 78, 85, 75, 91],
    'watch_rate': [0.95, 0.87, 0.99, 0.80, 0.93]
}
## DataFrame 생성
df = pd.DataFrame(data)

## CSV 형식 저장
df.to_csv('student_analysis.csv', encoding = 'utf-8', index = False)

## 5-2 JSON 형식 저장

In [14]:
### 라이브러리 임포트
import json
import pandas as pd

data = {
    "이름": "홍길동",
    "나이": 25,
    "거주지": "서울",
    "관심사": ["프로그래밍", "데이터 분석", "여행"]
}

## json.dump를 이용한 저장
with open('output.json', mode='w', encoding = 'utf-8') as f:
    json.dump(data, f, indent = 4, ensure_ascii = False)

## DataFrame을 이용한 저장
##df = pd.DataFrame(data) ## output_df.jason
df = pd.DataFrame([data]) ## 'output_df_1.json', orient='records'
df.to_json('output_df_2.json', orient='columns', indent = 4, force_ascii = False)

# json.dump를 이용한 저장

output.jason

{

    "이름": "홍길동",
    "나이": 25,
    "거주지": "서울",
    "관심사": [
        "프로그래밍",
        "데이터 분석",
        "여행"
    ]
}

# DataFrame을 이용한 저장

(1) df = pd.DataFrame(data) 일 때

output_df.jason

[

    {
        "이름":"홍길동",
        "나이":25,
        "거주지":"서울",
        "관심사":"프로그래밍"
    },
    {
        "이름":"홍길동",
        "나이":25,
        "거주지":"서울",
        "관심사":"데이터 분석"
    },
    {
        "이름":"홍길동",
        "나이":25,
        "거주지":"서울",
        "관심사":"여행"
    }
]

(2) df = pd.DataFrame([data]) 이고, orient='records' 일때

ouuput_df_1.json

[

    {
        "이름":"홍길동",
        "나이":25,
        "거주지":"서울",
        "관심사":[
            "프로그래밍",
            "데이터 분석",
            "여행"
        ]
    }
]

(3) df = pd.DataFrame([data]) 이고, orient='columns' 일때

output_df_2.json

{
    
    "이름":{
        "0":"홍길동"
    },
    "나이":{
        "0":25
    },
    "거주지":{
        "0":"서울"
    },
    "관심사":{
        "0":[
            "프로그래밍",
            "데이터 분석",
            "여행"
        ]
    }
}

## 5-3 Pandas Dataframe 데이터 추출

In [20]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터학", "경영학", "농학", "교육학", "영어영문학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}
df = pd.DataFrame(data)
df

## DataFrame 인덱스 출력
print(df.index)

## DataFrame 컬럼 출력
print(df.columns)

## DataFrame 행 출력
print(df.values.tolist())
print(df.values)

## DataFrame 값 출력
print(df.values.flatten())

RangeIndex(start=0, stop=5, step=1)
Index(['이름', '학년', '학점', '학과', '동아리'], dtype='object')
[['김철수', 1, 4.2, '컴퓨터학', '프로그래밍'], ['이영희', 2, 3.8, '경영학', '독서토론'], ['박민수', 3, 4.5, '농학', '로봇공학'], ['최지훈', 4, 3.9, '교육학', '봉사활동'], ['정소희', 2, 3.5, '영어영문학', '음악감상']]
[['김철수' 1 4.2 '컴퓨터학' '프로그래밍']
 ['이영희' 2 3.8 '경영학' '독서토론']
 ['박민수' 3 4.5 '농학' '로봇공학']
 ['최지훈' 4 3.9 '교육학' '봉사활동']
 ['정소희' 2 3.5 '영어영문학' '음악감상']]
['김철수' 1 4.2 '컴퓨터학' '프로그래밍' '이영희' 2 3.8 '경영학' '독서토론' '박민수' 3 4.5 '농학'
 '로봇공학' '최지훈' 4 3.9 '교육학' '봉사활동' '정소희' 2 3.5 '영어영문학' '음악감상']

## 5-4 DataFrame 생성 방법

In [32]:
import pandas as pd
import json

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

## 딕셔너리, csv, json으로 부터 DataFrame 생성
df1 = pd.DataFrame.from_dict(data)
## df1 = pd.DataFrame(data) 동일, 명확성과 추가적인 옵셥 활용을 위해
df2 = pd.read_csv('students.csv')
df3 = pd.read_json('students.json')

display(df1)
display(df2)
display(df3)


## 세가지 방법 결과 비교
print(df1.shape)
print(df2.shape)
print(df3.shape)

    이름  학년   학점     학과    동아리
0  김철수   1  4.2  컴퓨터공학  프로그래밍
1  이영희   2  3.8    경영학   독서토론
2  박민수   3  4.5   전자공학   로봇공학
3  최지훈   4  3.9     의학   봉사활동
4  정소희   2  3.5    심리학   음악감상

    학번   이름  데이터베이스  파이썬  클라우드
0  101  김철수      85   78    92
1  102  이영희      76   82    78
2  103  박지민      92   95    85
3  104  최준서      63   70    75
4  105  정미나      88   84    91

    id name  database  python  cloud
0  101  김철수        85      78     92
1  102  이영희        76      82     78
2  103  박지민        92      95     85
3  104  최준서        63      70     75
4  105  정미나        88      84     91

(5, 5)
(5, 5)
(5, 5)

## 5-5 DataFrame 저장 방법

In [37]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

## Dataframe 생성
df1 = pd.DataFrame(data)

## CSV, JSON 형식으로 저장
df.to_csv('students_score.csv')
df.to_json('students_score.json')

## HTML 형식으로 저장
html_table = df.to_html()
##print(html_table)
with open('students_score.html', 'w') as f:
    f.write(html_table)

## 5-6 실습 시나리오

## 데이터 수집

In [39]:
import requests

url ='https://apis.data.go.kr/B552584/ArpltnInforInqireSvc/getCtprvnRltmMesureDnsty'
api_key = 'mju0vTrfXFqpimjzrIFsVdxtM91NFaHvQvSyus3s8hkJ2d6v8Xwf/+DIknVjl+RTvg+mvhpNWtwGtb9RIx5GRA=='

params = {
    'serviceKey': api_key,
    'returnType': 'json',
    'numOfRows': '100',
    'pageNo': '1',
    'sidoName': '서울',
    'ver': '1.0'
}

## 데이터 수집
response = requests.get(url, params=params)

## 호출 성공/실패 출력
print(response.json())

{'response': {'body': {'totalCount': 40, 'items': [{'so2Grade': '1', 'coFlag': None, 'khaiValue': '28', 'so2Value': '0.002', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '9', 'khaiGrade': '1', 'pm25Value': '7', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.017', 'stationName': '중구', 'pm10Grade': '1', 'o3Value': '0.012'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '24', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '9', 'khaiGrade': '1', 'pm25Value': '5', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.014', 'stationName': '한강대로', 'pm10Grade': '1', 'o3Value': '0.015'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '-', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '13', 'khaiGrade': None, 'pm25Value': '9', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': None, 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.013', 'stationName': '종로구', 'pm10Grade': None, 'o3Value': '0.009'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '29', 'so2Value': '0.003', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '8', 'khaiGrade': '1', 'pm25Value': '4', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.017', 'stationName': '청계천로', 'pm10Grade': '1', 'o3Value': '0.003'}, {'so2Grade': None, 'coFlag': '통신장애', 'khaiValue': '-', 'so2Value': '-', 'coValue': '-', 'pm25Flag': '통신장애', 'pm10Flag': '통신장애', 'o3Grade': None, 'pm10Value': '-', 'khaiGrade': None, 'pm25Value': '-', 'sidoName': '서울', 'no2Flag': '통신장애', 'no2Grade': None, 'o3Flag': '통신장애', 'pm25Grade': '1', 'so2Flag': '통신장애', 'dataTime': '2026-08-31 14:00', 'coGrade': None, 'no2Value': '-', 'stationName': '종로', 'pm10Grade': '1', 'o3Value': '-'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '20', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '8', 'khaiGrade': '1', 'pm25Value': '3', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.012', 'stationName': '용산구', 'pm10Grade': '1', 'o3Value': '0.010'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '25', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': '통신장애', 'pm10Flag': '통신장애', 'o3Grade': '1', 'pm10Value': '-', 'khaiGrade': '1', 'pm25Value': '-', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.007', 'stationName': '광진구', 'pm10Grade': '1', 'o3Value': '0.014'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '25', 'so2Value': '0.003', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '9', 'khaiGrade': '1', 'pm25Value': '1', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.009', 'stationName': '성동구', 'pm10Grade': '1', 'o3Value': '0.015'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '24', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '8', 'khaiGrade': '1', 'pm25Value': '3', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.015', 'stationName': '강변북로', 'pm10Grade': '1', 'o3Value': '0.011'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '22', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '10', 'khaiGrade': '1', 'pm25Value': '5', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.008', 'stationName': '중랑구', 'pm10Grade': '1', 'o3Value': '0.013'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '27', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '11', 'khaiGrade': '1', 'pm25Value': '7', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.011', 'stationName': '동대문구', 'pm10Grade': '1', 'o3Value': '0.012'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '36', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '8', 'khaiGrade': '1', 'pm25Value': '3', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.022', 'stationName': '홍릉로', 'pm10Grade': '1', 'o3Value': '0.013'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '22', 'so2Value': '0.003', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '6', 'khaiGrade': '1', 'pm25Value': '2', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.010', 'stationName': '성북구', 'pm10Grade': '1', 'o3Value': '0.013'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '26', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '11', 'khaiGrade': '1', 'pm25Value': '7', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.016', 'stationName': '정릉로', 'pm10Grade': '1', 'o3Value': '0.010'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '29', 'so2Value': '0.003', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '6', 'khaiGrade': '1', 'pm25Value': '1', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.005', 'stationName': '도봉구', 'pm10Grade': '1', 'o3Value': '0.017'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '30', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '7', 'khaiGrade': '1', 'pm25Value': '3', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.006', 'stationName': '은평구', 'pm10Grade': '1', 'o3Value': '0.018'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '37', 'so2Value': '0.003', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '11', 'khaiGrade': '1', 'pm25Value': '1', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.006', 'stationName': '서대문구', 'pm10Grade': '1', 'o3Value': '0.022'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '21', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '8', 'khaiGrade': '1', 'pm25Value': '3', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.013', 'stationName': '마포구', 'pm10Grade': '1', 'o3Value': '0.013'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '28', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '11', 'khaiGrade': '1', 'pm25Value': '6', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.017', 'stationName': '신촌로', 'pm10Grade': '1', 'o3Value': '0.011'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '26', 'so2Value': '0.003', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '4', 'khaiGrade': '1', 'pm25Value': '4', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.016', 'stationName': '강서구', 'pm10Grade': '1', 'o3Value': '0.013'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '33', 'so2Value': '0.001', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '13', 'khaiGrade': '1', 'pm25Value': '5', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.019', 'stationName': '공항대로', 'pm10Grade': '1', 'o3Value': '0.011'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '25', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '3', 'khaiGrade': '1', 'pm25Value': '1', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.012', 'stationName': '구로구', 'pm10Grade': '1', 'o3Value': '0.015'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '26', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '8', 'khaiGrade': '1', 'pm25Value': '5', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.016', 'stationName': '영등포구', 'pm10Grade': '1', 'o3Value': '0.011'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '33', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '9', 'khaiGrade': '1', 'pm25Value': '7', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.020', 'stationName': '영등포로', 'pm10Grade': '1', 'o3Value': '0.006'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '22', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '5', 'khaiGrade': '1', 'pm25Value': '2', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.013', 'stationName': '동작구', 'pm10Grade': '1', 'o3Value': '0.010'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '37', 'so2Value': '0.003', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '10', 'khaiGrade': '1', 'pm25Value': '10', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.019', 'stationName': '동작대로 중앙차로', 'pm10Grade': '1', 'o3Value': '0.005'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '25', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '10', 'khaiGrade': '1', 'pm25Value': '5', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.012', 'stationName': '관악구', 'pm10Grade': '1', 'o3Value': '0.014'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '23', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '9', 'khaiGrade': '1', 'pm25Value': '2', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.014', 'stationName': '강남구', 'pm10Grade': '1', 'o3Value': '0.010'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '33', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '13', 'khaiGrade': '1', 'pm25Value': '10', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.015', 'stationName': '서초구', 'pm10Grade': '1', 'o3Value': '0.010'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '22', 'so2Value': '0.002', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '9', 'khaiGrade': '1', 'pm25Value': '3', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.013', 'stationName': '도산대로', 'pm10Grade': '1', 'o3Value': '0.013'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '23', 'so2Value': '0.003', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '15', 'khaiGrade': '1', 'pm25Value': '4', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.014', 'stationName': '강남대로', 'pm10Grade': '1', 'o3Value': '0.009'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '20', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '8', 'khaiGrade': '1', 'pm25Value': '4', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.011', 'stationName': '송파구', 'pm10Grade': '1', 'o3Value': '0.011'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '25', 'so2Value': '0.002', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '3', 'khaiGrade': '1', 'pm25Value': '1', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.008', 'stationName': '강동구', 'pm10Grade': '1', 'o3Value': '0.015'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '27', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '11', 'khaiGrade': '1', 'pm25Value': '3', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.016', 'stationName': '천호대로', 'pm10Grade': '1', 'o3Value': '0.005'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '22', 'so2Value': '0.003', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '3', 'khaiGrade': '1', 'pm25Value': '4', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.009', 'stationName': '금천구', 'pm10Grade': '1', 'o3Value': '0.013'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '43', 'so2Value': '0.002', 'coValue': '0.6', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '18', 'khaiGrade': '1', 'pm25Value': '6', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.026', 'stationName': '시흥대로', 'pm10Grade': '1', 'o3Value': '0.003'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '30', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '7', 'khaiGrade': '1', 'pm25Value': '3', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.007', 'stationName': '강북구', 'pm10Grade': '1', 'o3Value': '0.018'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '24', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '7', 'khaiGrade': '1', 'pm25Value': '3', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.014', 'stationName': '양천구', 'pm10Grade': '1', 'o3Value': '0.014'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '27', 'so2Value': '0.002', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '7', 'khaiGrade': '1', 'pm25Value': '5', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.007', 'stationName': '노원구', 'pm10Grade': '1', 'o3Value': '0.016'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '27', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '13', 'khaiGrade': '1', 'pm25Value': '5', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.016', 'stationName': '화랑로', 'pm10Grade': '1', 'o3Value': '0.007'}], 'pageNo': 1, 'numOfRows': 100}, 'header': {'resultMsg': 'NORMAL_CODE', 'resultCode': '00'}}}

In [41]:
response.json()

{'response': {'body': {'totalCount': 40,
   'items': [{'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '28',
     'so2Value': '0.002',
     'coValue': '0.5',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '9',
     'khaiGrade': '1',
     'pm25Value': '7',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.017',
     'stationName': '중구',
     'pm10Grade': '1',
     'o3Value': '0.012'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '24',
     'so2Value': '0.002',
     'coValue': '0.4',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '9',
     'khaiGrade': '1',
     'pm25Value': '5',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.014',
     'stationName': '한강대로',
     'pm10Grade': '1',
     'o3Value': '0.015'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '-',
     'so2Value': '0.002',
     'coValue': '0.3',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '13',
     'khaiGrade': None,
     'pm25Value': '9',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': None,
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.013',
     'stationName': '종로구',
     'pm10Grade': None,
     'o3Value': '0.009'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '29',
     'so2Value': '0.003',
     'coValue': '0.5',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '8',
     'khaiGrade': '1',
     'pm25Value': '4',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.017',
     'stationName': '청계천로',
     'pm10Grade': '1',
     'o3Value': '0.003'},
    {'so2Grade': None,
     'coFlag': '통신장애',
     'khaiValue': '-',
     'so2Value': '-',
     'coValue': '-',
     'pm25Flag': '통신장애',
     'pm10Flag': '통신장애',
     'o3Grade': None,
     'pm10Value': '-',
     'khaiGrade': None,
     'pm25Value': '-',
     'sidoName': '서울',
     'no2Flag': '통신장애',
     'no2Grade': None,
     'o3Flag': '통신장애',
     'pm25Grade': '1',
     'so2Flag': '통신장애',
     'dataTime': '2026-08-31 14:00',
     'coGrade': None,
     'no2Value': '-',
     'stationName': '종로',
     'pm10Grade': '1',
     'o3Value': '-'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '20',
     'so2Value': '0.002',
     'coValue': '0.3',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '8',
     'khaiGrade': '1',
     'pm25Value': '3',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.012',
     'stationName': '용산구',
     'pm10Grade': '1',
     'o3Value': '0.010'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '25',
     'so2Value': '0.002',
     'coValue': '0.3',
     'pm25Flag': '통신장애',
     'pm10Flag': '통신장애',
     'o3Grade': '1',
     'pm10Value': '-',
     'khaiGrade': '1',
     'pm25Value': '-',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.007',
     'stationName': '광진구',
     'pm10Grade': '1',
     'o3Value': '0.014'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '25',
     'so2Value': '0.003',
     'coValue': '0.3',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '9',
     'khaiGrade': '1',
     'pm25Value': '1',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.009',
     'stationName': '성동구',
     'pm10Grade': '1',
     'o3Value': '0.015'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '24',
     'so2Value': '0.002',
     'coValue': '0.3',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '8',
     'khaiGrade': '1',
     'pm25Value': '3',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.015',
     'stationName': '강변북로',
     'pm10Grade': '1',
     'o3Value': '0.011'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '22',
     'so2Value': '0.002',
     'coValue': '0.3',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '10',
     'khaiGrade': '1',
     'pm25Value': '5',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.008',
     'stationName': '중랑구',
     'pm10Grade': '1',
     'o3Value': '0.013'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '27',
     'so2Value': '0.002',
     'coValue': '0.3',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '11',
     'khaiGrade': '1',
     'pm25Value': '7',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.011',
     'stationName': '동대문구',
     'pm10Grade': '1',
     'o3Value': '0.012'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '36',
     'so2Value': '0.002',
     'coValue': '0.3',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '8',
     'khaiGrade': '1',
     'pm25Value': '3',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.022',
     'stationName': '홍릉로',
     'pm10Grade': '1',
     'o3Value': '0.013'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '22',
     'so2Value': '0.003',
     'coValue': '0.3',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '6',
     'khaiGrade': '1',
     'pm25Value': '2',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.010',
     'stationName': '성북구',
     'pm10Grade': '1',
     'o3Value': '0.013'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '26',
     'so2Value': '0.002',
     'coValue': '0.3',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '11',
     'khaiGrade': '1',
     'pm25Value': '7',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.016',
     'stationName': '정릉로',
     'pm10Grade': '1',
     'o3Value': '0.010'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '29',
     'so2Value': '0.003',
     'coValue': '0.2',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '6',
     'khaiGrade': '1',
     'pm25Value': '1',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.005',
     'stationName': '도봉구',
     'pm10Grade': '1',
     'o3Value': '0.017'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '30',
     'so2Value': '0.002',
     'coValue': '0.3',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '7',
     'khaiGrade': '1',
     'pm25Value': '3',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.006',
     'stationName': '은평구',
     'pm10Grade': '1',
     'o3Value': '0.018'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '37',
     'so2Value': '0.003',
     'coValue': '0.3',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '11',
     'khaiGrade': '1',
     'pm25Value': '1',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.006',
     'stationName': '서대문구',
     'pm10Grade': '1',
     'o3Value': '0.022'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '21',
     'so2Value': '0.002',
     'coValue': '0.3',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '8',
     'khaiGrade': '1',
     'pm25Value': '3',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.013',
     'stationName': '마포구',
     'pm10Grade': '1',
     'o3Value': '0.013'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '28',
     'so2Value': '0.002',
     'coValue': '0.4',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '11',
     'khaiGrade': '1',
     'pm25Value': '6',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.017',
     'stationName': '신촌로',
     'pm10Grade': '1',
     'o3Value': '0.011'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '26',
     'so2Value': '0.003',
     'coValue': '0.4',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '4',
     'khaiGrade': '1',
     'pm25Value': '4',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.016',
     'stationName': '강서구',
     'pm10Grade': '1',
     'o3Value': '0.013'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '33',
     'so2Value': '0.001',
     'coValue': '0.4',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '13',
     'khaiGrade': '1',
     'pm25Value': '5',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.019',
     'stationName': '공항대로',
     'pm10Grade': '1',
     'o3Value': '0.011'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '25',
     'so2Value': '0.002',
     'coValue': '0.3',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '3',
     'khaiGrade': '1',
     'pm25Value': '1',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.012',
     'stationName': '구로구',
     'pm10Grade': '1',
     'o3Value': '0.015'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '26',
     'so2Value': '0.002',
     'coValue': '0.4',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '8',
     'khaiGrade': '1',
     'pm25Value': '5',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.016',
     'stationName': '영등포구',
     'pm10Grade': '1',
     'o3Value': '0.011'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '33',
     'so2Value': '0.002',
     'coValue': '0.4',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '9',
     'khaiGrade': '1',
     'pm25Value': '7',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.020',
     'stationName': '영등포로',
     'pm10Grade': '1',
     'o3Value': '0.006'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '22',
     'so2Value': '0.002',
     'coValue': '0.3',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '5',
     'khaiGrade': '1',
     'pm25Value': '2',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.013',
     'stationName': '동작구',
     'pm10Grade': '1',
     'o3Value': '0.010'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '37',
     'so2Value': '0.003',
     'coValue': '0.4',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '10',
     'khaiGrade': '1',
     'pm25Value': '10',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.019',
     'stationName': '동작대로 중앙차로',
     'pm10Grade': '1',
     'o3Value': '0.005'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '25',
     'so2Value': '0.002',
     'coValue': '0.3',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '10',
     'khaiGrade': '1',
     'pm25Value': '5',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.012',
     'stationName': '관악구',
     'pm10Grade': '1',
     'o3Value': '0.014'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '23',
     'so2Value': '0.002',
     'coValue': '0.3',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '9',
     'khaiGrade': '1',
     'pm25Value': '2',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.014',
     'stationName': '강남구',
     'pm10Grade': '1',
     'o3Value': '0.010'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '33',
     'so2Value': '0.002',
     'coValue': '0.3',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '13',
     'khaiGrade': '1',
     'pm25Value': '10',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.015',
     'stationName': '서초구',
     'pm10Grade': '1',
     'o3Value': '0.010'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '22',
     'so2Value': '0.002',
     'coValue': '0.5',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '9',
     'khaiGrade': '1',
     'pm25Value': '3',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.013',
     'stationName': '도산대로',
     'pm10Grade': '1',
     'o3Value': '0.013'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '23',
     'so2Value': '0.003',
     'coValue': '0.4',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '15',
     'khaiGrade': '1',
     'pm25Value': '4',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.014',
     'stationName': '강남대로',
     'pm10Grade': '1',
     'o3Value': '0.009'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '20',
     'so2Value': '0.002',
     'coValue': '0.3',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '8',
     'khaiGrade': '1',
     'pm25Value': '4',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.011',
     'stationName': '송파구',
     'pm10Grade': '1',
     'o3Value': '0.011'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '25',
     'so2Value': '0.002',
     'coValue': '0.2',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '3',
     'khaiGrade': '1',
     'pm25Value': '1',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.008',
     'stationName': '강동구',
     'pm10Grade': '1',
     'o3Value': '0.015'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '27',
     'so2Value': '0.002',
     'coValue': '0.4',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '11',
     'khaiGrade': '1',
     'pm25Value': '3',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.016',
     'stationName': '천호대로',
     'pm10Grade': '1',
     'o3Value': '0.005'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '22',
     'so2Value': '0.003',
     'coValue': '0.3',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '3',
     'khaiGrade': '1',
     'pm25Value': '4',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.009',
     'stationName': '금천구',
     'pm10Grade': '1',
     'o3Value': '0.013'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '43',
     'so2Value': '0.002',
     'coValue': '0.6',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '18',
     'khaiGrade': '1',
     'pm25Value': '6',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '1',
     'so2Flag': None,
     'dataTime': '2026-08-31 14:00',
     'coGrade': '1',
     'no2Value': '0.026',
     'stationName': '시흥대로',
     'pm10Grade': '1',
     'o3Value': '0.003'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '30',
     'so2Value': '0.002',
     'coValue': '0.3',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '7',
     'khaiGrade': '1',
     'pm25Value': '3',
     'sidoName': '서울',

## 데이터 프레임 생성

In [46]:
import pandas as pd

## requests로부터 response, body, item 항목 읽기
data = response.json()['response']['body']['items']
print(type(data))
print(len(data))
print(data[0])

df = pd.DataFrame(data)
##df
df['pm25Grade']

<class 'list'>
40
{'so2Grade': '1', 'coFlag': None, 'khaiValue': '28', 'so2Value': '0.002', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '9', 'khaiGrade': '1', 'pm25Value': '7', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-08-31 14:00', 'coGrade': '1', 'no2Value': '0.017', 'stationName': '중구', 'pm10Grade': '1', 'o3Value': '0.012'}

0        1
1        1
2     None
3        1
4        1
5        1
6        1
7        1
8        1
9        1
10       1
11       1
12       1
13       1
14       1
15       1
16       1
17       1
18       1
19       1
20       1
21       1
22       1
23       1
24       1
25       1
26       1
27       1
28       1
29       1
30       1
31       1
32       1
33       1
34       1
35       1
36       1
37       1
38       1
39       1
Name: pm25Grade, dtype: object

## 다양항 형식으로 데이터 저장

In [47]:
## CSV 형식 데이터 저장
df.to_csv('air_pollution.csv', index=False, encoding='utf-8')

## JSON 형식 데이터 저장
df.to_json('air_pollution.json', indent=4, force_ascii=False)

## EXCEL 형식 데이터 저장
df.to_excel('air_pollution.xlsx', index=False)

## HTML 형식 데이터 저장
df.to_html('air_pollution.html')